import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { FaArrowLeft, FaCar, FaEdit, FaFileExcel, FaFilePdf, FaImage, FaPlus, FaPrint, FaSearch, FaTrash } from 'react-icons/fa'
import { useLanding } from '../../landing/LandingContext'
import { useAuthStore } from '../../../store/authStore'
import { branchManagementService } from '../../../services/branchManagementService'
import { getPicoYPlacaInfo, VEHICLE_STATES, vehicleManagementService } from '../../../services/vehicleManagementService'
import { exportExcel, exportPdf, printTable } from '../../../utils/listExportUtils'
import MenuConfiguracion from '../../../components/MenuConfiguracion'
import './CityManagementPage.css'
import './VehicleManagementPage.css'

const EMPTY = { nombre: '', placa: '', categoria: 'Sedan', transmision: 'Automática', combustible: 'Gasolina', color: '', año: new Date().getFullYear(), sucursal: '', descripcion: '', estadoFlota: VEHICLE_STATES.AVAILABLE, puertas: 4, pasajeros: 5, maletero: 0, cilindraje: '', destacado: false, kmLimitado: 200, precioLimitado: 0, precioExcedente: 0, precioIlimitado: 0, caracteristicasTexto: '', equipamientoTecnologico: [], seguros: [{ nombre: 'Protección Obligatoria', precio: 29000 }], imagenes: [] }
const listToText = (items) => (items || []).map((item) => item.nombre).join(', ')
const textToList = (text) => String(text || '').split(',').map((nombre) => nombre.trim()).filter(Boolean).map((nombre) => ({ nombre, icono: 'FaCheckCircle' }))

export default function VehicleManagementPage() {
  const { t } = useTranslation(); const { tema } = useLanding(); const user = useAuthStore((state) => state.usuario)
  const [vehicles, setVehicles] = useState(() => vehicleManagementService.list()); const [search, setSearch] = useState(''); const [branchFilter, setBranchFilter] = useState('all'); const [stateFilter, setStateFilter] = useState('all'); const [modal, setModal] = useState(null); const [form, setForm] = useState(EMPTY); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const branches = branchManagementService.list().sort((a, b) => a.nombre.localeCompare(b.nombre))
  const filtered = useMemo(() => { const term = search.trim().toLocaleLowerCase(); return vehicles.filter((vehicle) => (branchFilter === 'all' || vehicle.sucursal === branchFilter) && (stateFilter === 'all' || vehicle.estadoEfectivo === stateFilter) && (!term || `${vehicle.nombre} ${vehicle.placa} ${vehicle.categoria} ${vehicle.sucursal}`.toLocaleLowerCase().includes(term))).sort((a, b) => a.nombre.localeCompare(b.nombre)) }, [branchFilter, search, stateFilter, vehicles])
  const headers = [t('admin.vehiclesManagement.fields.vehicle'), t('admin.vehiclesManagement.fields.plate'), t('admin.vehiclesManagement.fields.branch'), t('admin.vehiclesManagement.fields.category'), t('admin.vehiclesManagement.fields.state'), t('admin.vehiclesManagement.fields.price'), t('admin.vehiclesManagement.fields.pico')]
  const rows = filtered.map((vehicle) => [vehicle.nombre, vehicle.placa, vehicle.sucursal, vehicle.categoria, t(`admin.vehiclesManagement.states.${vehicle.estadoEfectivo}`), vehicle.precio, vehicle.picoYPlaca.dia || '—'])
  const exportData = { title: t('admin.vehiclesManagement.exportTitle'), headers, rows, filename: 'flota-drivique' }
  const close = () => { setModal(null); setError('') }
  const openCreate = () => { setForm({ ...EMPTY, sucursal: branches[0]?.nombre || '' }); setModal({ type: 'form' }); setError('') }
  const openEdit = (vehicle) => { setForm({ ...vehicle, estadoFlota: vehicle.estadoFlota, kmLimitado: vehicle.tarifas?.kmLimitado?.km || 0, precioLimitado: vehicle.tarifas?.kmLimitado?.precio || vehicle.precio || 0, precioExcedente: vehicle.tarifas?.kmLimitado?.excedente || 0, precioIlimitado: vehicle.tarifas?.kmIlimitado?.precio || 0, caracteristicasTexto: listToText(vehicle.caracteristicas), seguros: vehicle.seguros || [], imagenes: vehicle.imagenes || [] }); setModal({ type: 'form', vehicle }); setError('') }
  const save = (event) => { event.preventDefault(); const payload = { ...form, caracteristicas: textToList(form.caracteristicasTexto) }; try { if (modal.vehicle) vehicleManagementService.update(modal.vehicle.id, payload, user); else vehicleManagementService.create(payload, user); setVehicles(vehicleManagementService.list()); setNotice(t(modal.vehicle ? 'admin.vehiclesManagement.messages.updated' : 'admin.vehiclesManagement.messages.created')); close() } catch (caught) { setError(t(`admin.vehiclesManagement.errors.${caught.message}`)) } }
  const remove = () => { try { vehicleManagementService.remove(modal.vehicle.id, user); setVehicles(vehicleManagementService.list()); setNotice(t('admin.vehiclesManagement.messages.deleted')); close() } catch (caught) { setModal(null); setNotice(t(`admin.vehiclesManagement.errors.${caught.message}`, { count: caught.count })) } }
  const addInsurance = () => setForm({ ...form, seguros: [...form.seguros, { nombre: '', precio: 0 }] })
  const updateInsurance = (index, key, value) => setForm({ ...form, seguros: form.seguros.map((insurance, current) => current === index ? { ...insurance, [key]: key === 'precio' ? Number(value) : value } : insurance) })
  const loadImages = async (event) => { const files = [...event.target.files].slice(0, Math.max(0, 3 - form.imagenes.length)); if (files.some((file) => file.size > 1024 * 1024)) { setError(t('admin.vehiclesManagement.errors.imageSize')); return } const images = await Promise.all(files.map((file) => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file) }))); setForm((current) => ({ ...current, imagenes: [...current.imagenes, ...images].slice(0, 3) })) }
  const pico = getPicoYPlacaInfo(form.placa, form.sucursal)

  return <main className={`cities-page fleet-admin ${tema === 'oscuro' ? 'cities-page--dark' : ''}`}><div className="cities-container"><header className="cities-topbar"><div><Link className="cities-back" to="/admin"><FaArrowLeft /> {t('admin.backToDashboard')}</Link><p className="cities-eyebrow">{t('admin.management')}</p><h1>{t('admin.vehiclesManagement.title')}</h1><p className="cities-subtitle">{t('admin.vehiclesManagement.subtitle')}</p></div><div className="cities-topbar__actions"><MenuConfiguracion /><button className="cities-primary" type="button" onClick={openCreate}><FaPlus /> {t('admin.vehiclesManagement.create')}</button></div></header>
    {notice && <div className="cities-notice" role="status"><span>{notice}</span><button type="button" onClick={() => setNotice('')}>×</button></div>}
    <section className="cities-card"><div className="fleet-toolbar"><label className="cities-search"><FaSearch /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t('admin.vehiclesManagement.search')} /></label><select value={branchFilter} onChange={(event) => setBranchFilter(event.target.value)}><option value="all">{t('admin.vehiclesManagement.allBranches')}</option>{branches.map((branch) => <option key={branch.id} value={branch.nombre}>{branch.nombre}</option>)}</select><select value={stateFilter} onChange={(event) => setStateFilter(event.target.value)}><option value="all">{t('admin.vehiclesManagement.allStates')}</option>{Object.values(VEHICLE_STATES).map((state) => <option key={state} value={state}>{t(`admin.vehiclesManagement.states.${state}`)}</option>)}</select><div className="cities-export"><button type="button" onClick={() => exportExcel(exportData)}><FaFileExcel /> Excel</button><button type="button" onClick={() => exportPdf(exportData)}><FaFilePdf /> PDF</button><button type="button" onClick={() => printTable(exportData)}><FaPrint /> {t('admin.cities.print')}</button></div></div><div className="cities-summary"><strong>{filtered.length}</strong> {t('admin.vehiclesManagement.results')}</div>
      {filtered.length === 0 ? <div className="cities-empty"><FaCar /><h2>{t('admin.vehiclesManagement.emptyTitle')}</h2></div> : <div className="cities-table-wrap"><table className="fleet-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}<th>{t('admin.cities.fields.actions')}</th></tr></thead><tbody>{filtered.map((vehicle) => <tr key={vehicle.id}><td><div className="fleet-vehicle">{vehicle.imagenes?.[0] ? <img src={vehicle.imagenes[0]} alt="" /> : <span><FaCar /></span>}<div><strong>{vehicle.nombre}</strong><small>{vehicle.año} · {vehicle.color}</small></div></div></td><td><strong>{vehicle.placa}</strong></td><td>{vehicle.sucursal}</td><td>{vehicle.categoria}</td><td><span className={`fleet-state is-${vehicle.estadoEfectivo}`}>{t(`admin.vehiclesManagement.states.${vehicle.estadoEfectivo}`)}</span></td><td>{vehicle.precio}</td><td>{vehicle.picoYPlaca.dia ? t(`vehiculo.picoYPlaca.dias.${vehicle.picoYPlaca.dia}`) : '—'}</td><td><div className="cities-row-actions"><button type="button" onClick={() => openEdit(vehicle)}><FaEdit /></button><button className="is-danger" type="button" onClick={() => setModal({ type: 'delete', vehicle })}><FaTrash /></button></div></td></tr>)}</tbody></table></div>}
    </section></div>
    {modal && <div className="cities-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && close()}><section className="cities-modal fleet-modal" role="dialog" aria-modal="true">{modal.type === 'form' ? <><div className="cities-modal__head"><div><p className="cities-eyebrow">{t('admin.vehiclesManagement.formLabel')}</p><h2>{t(modal.vehicle ? 'admin.vehiclesManagement.editTitle' : 'admin.vehiclesManagement.createTitle')}</h2></div><button type="button" onClick={close}>×</button></div><form onSubmit={save}><fieldset><legend>{t('admin.vehiclesManagement.sections.general')}</legend><div className="fleet-form-grid"><label>{t('admin.vehiclesManagement.fields.vehicle')}<input value={form.nombre} onChange={(event) => setForm({ ...form, nombre: event.target.value })} /></label><label>{t('admin.vehiclesManagement.fields.plate')}<input value={form.placa} onChange={(event) => setForm({ ...form, placa: event.target.value.toUpperCase() })} /><small>{pico.dia ? `${t('admin.vehiclesManagement.picoResult')}: ${t(`vehiculo.picoYPlaca.dias.${pico.dia}`)}` : t('admin.vehiclesManagement.picoPending')}</small></label><label>{t('admin.vehiclesManagement.fields.branch')}<select value={form.sucursal} onChange={(event) => setForm({ ...form, sucursal: event.target.value })}>{branches.map((branch) => <option key={branch.id}>{branch.nombre}</option>)}</select></label><label>{t('admin.vehiclesManagement.fields.state')}<select value={form.estadoFlota} onChange={(event) => setForm({ ...form, estadoFlota: event.target.value })}>{Object.values(VEHICLE_STATES).map((state) => <option key={state} value={state}>{t(`admin.vehiclesManagement.states.${state}`)}</option>)}</select></label>{[['categoria','category'],['transmision','transmission'],['combustible','fuel']].map(([key,label]) => <label key={key}>{t(`admin.vehiclesManagement.fields.${label}`)}<input value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}<label>{t('admin.vehiclesManagement.fields.color')}<input value={form.color} onChange={(event) => setForm({ ...form, color: event.target.value })} /></label><label>{t('admin.vehiclesManagement.fields.year')}<input type="number" value={form.año} onChange={(event) => setForm({ ...form, año: event.target.value })} /></label></div></fieldset>
      <fieldset><legend>{t('admin.vehiclesManagement.sections.features')}</legend><div className="fleet-form-grid">{[['puertas','doors'],['pasajeros','passengers'],['maletero','trunk']].map(([key,label]) => <label key={key}>{t(`admin.vehiclesManagement.fields.${label}`)}<input type="number" value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}<label>{t('admin.vehiclesManagement.fields.engine')}<input value={form.cilindraje} onChange={(event) => setForm({ ...form, cilindraje: event.target.value })} /></label></div><label>{t('admin.vehiclesManagement.fields.features')}<input value={form.caracteristicasTexto} onChange={(event) => setForm({ ...form, caracteristicasTexto: event.target.value })} placeholder={t('admin.vehiclesManagement.featuresHint')} /></label><label>{t('admin.vehiclesManagement.fields.description')}<textarea value={form.descripcion} onChange={(event) => setForm({ ...form, descripcion: event.target.value })} /></label></fieldset>
      <fieldset><legend>{t('admin.vehiclesManagement.sections.rates')}</legend><div className="fleet-form-grid">{[['kmLimitado','limitedKm'],['precioLimitado','limitedPrice'],['precioExcedente','extraPrice'],['precioIlimitado','unlimitedPrice']].map(([key,label]) => <label key={key}>{t(`admin.vehiclesManagement.fields.${label}`)}<input type="number" min="0" value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}</div><div className="fleet-insurances">{form.seguros.map((insurance,index) => <div key={index}><input value={insurance.nombre} onChange={(event) => updateInsurance(index,'nombre',event.target.value)} placeholder={t('admin.vehiclesManagement.insuranceName')} /><input type="number" value={insurance.precio} onChange={(event) => updateInsurance(index,'precio',event.target.value)} /><button type="button" onClick={() => setForm({ ...form, seguros: form.seguros.filter((_,current) => current !== index) })} aria-label={t('common.delete')}>×</button></div>)}<button type="button" onClick={addInsurance}><FaPlus /> {t('admin.vehiclesManagement.addInsurance')}</button></div></fieldset>
      <fieldset><legend>{t('admin.vehiclesManagement.sections.images')}</legend><label className="fleet-upload"><FaImage /><span>{t('admin.vehiclesManagement.uploadImages')}</span><input type="file" accept="image/*" multiple onChange={loadImages} /></label><div className="fleet-images">{form.imagenes.map((image,index) => <div key={`${String(image).slice(-20)}-${index}`}><img src={image} alt="" /><button type="button" onClick={() => setForm({ ...form, imagenes: form.imagenes.filter((_,current) => current !== index) })}>×</button></div>)}</div></fieldset>{error && <p className="cities-error">{error}</p>}<div className="cities-modal__actions"><button type="button" onClick={close}>{t('common.cancel')}</button><button className="cities-primary" type="submit">{t('common.save')}</button></div></form></> : <><div className="cities-delete-icon"><FaTrash /></div><h2>{t('admin.vehiclesManagement.deleteTitle')}</h2><p>{t('admin.vehiclesManagement.deleteText', { vehicle: modal.vehicle.nombre })}</p><div className="cities-modal__actions"><button type="button" onClick={close}>{t('common.cancel')}</button><button className="cities-danger" type="button" onClick={remove}>{t('common.delete')}</button></div></>}</section></div>}
  </main>
}
