import { useState, useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { authService, DURACION_CODIGO_VERIFICACION_MS } from '../../../services/authService'
import { useAuthStore } from '../../../store/authStore'
const LARGO_CODIGO = 6; const TIEMPO_REENVIO = 60; const SEGUNDOS_EXPIRACION_INICIAL = Math.floor(DURACION_CODIGO_VERIFICACION_MS / 1000)
export function useVerifyRecover() {
  const navigate = useNavigate(); const recuperacion = useAuthStore((s) => s.recuperacionCorreo); const iniciarRecuperacionCorreo = useAuthStore((s) => s.iniciarRecuperacionCorreo); const cancelarRecuperacionCorreo = useAuthStore((s) => s.cancelarRecuperacionCorreo); const recuperacionCorreo = recuperacion?.correo
  const [codigo, setCodigo] = useState(''); const [cargando, setCargando] = useState(false); const [error, setError] = useState(''); const [segundosReenvio, setSegundosReenvio] = useState(TIEMPO_REENVIO); const [segundosExpiracion, setSegundosExpiracion] = useState(SEGUNDOS_EXPIRACION_INICIAL); const [reenviando, setReenviando] = useState(false); const inputsRef = useRef([]); const expirado = segundosExpiracion <= 0
  useEffect(() => { if (segundosReenvio <= 0) return; const t = setInterval(() => setSegundosReenvio((s) => s - 1), 1000); return () => clearInterval(t) }, [segundosReenvio]); useEffect(() => { if (expirado) return; const t = setInterval(() => setSegundosExpiracion((s) => Math.max(0, s - 1)), 1000); return () => clearInterval(t) }, [expirado]); useEffect(() => { inputsRef.current[0]?.focus() }, [])
  const autoSubmit = async (codigoCompleto) => { if (!recuperacionCorreo || expirado) return; setCargando(true); setError(''); try { await authService.verificarCodigoRecuperacion(recuperacionCorreo, codigoCompleto); iniciarRecuperacionCorreo(recuperacionCorreo, codigoCompleto); navigate('/nueva-contrasena') } catch (err) { setError(err?.response?.data?.mensaje || err?.response?.data?.message || 'Código inválido.') } finally { setCargando(false) } }
  const handleCambioDigito = (index, value) => { if (!/^[0-9]*$/.test(value)) return; setError(''); const chars = codigo.split(''); chars[index] = value.slice(-1); const next = chars.join(''); setCodigo(next); if (value && index < LARGO_CODIGO - 1) inputsRef.current[index + 1]?.focus(); if (next.length === LARGO_CODIGO) autoSubmit(next) }; const handleKeyDown = (index, e) => { if (e.key === 'Backspace' && !codigo[index] && index > 0) inputsRef.current[index - 1]?.focus() }; const handlePaste = (e) => { e.preventDefault(); const pasted = e.clipboardData.getData('text').replace(/\D/g, '').slice(0, LARGO_CODIGO); if (!pasted) return; setCodigo(pasted); setError(''); if (pasted.length === LARGO_CODIGO) autoSubmit(pasted); else inputsRef.current[pasted.length]?.focus() }; const handleSubmit = (e) => { e.preventDefault(); if (codigo.length === LARGO_CODIGO) autoSubmit(codigo) }; const handleReenviar = async () => { if (!recuperacionCorreo) return; setReenviando(true); setError(''); try { await authService.solicitarRecuperacion(recuperacionCorreo); setSegundosReenvio(TIEMPO_REENVIO); setSegundosExpiracion(SEGUNDOS_EXPIRACION_INICIAL); setCodigo('') } catch (err) { setError(err?.response?.data?.mensaje || err?.response?.data?.message || 'Error al reenviar.') } finally { setReenviando(false) } }; const handleCancelar = () => { cancelarRecuperacionCorreo(); navigate('/login') }
  return { correo: recuperacionCorreo, codigo, cargando, error, expirado, segundosReenvio, segundosExpiracion, reenviando, inputsRef, LARGO_CODIGO, handleCambioDigito, handleKeyDown, handlePaste, handleSubmit, handleReenviar, handleCancelar }
}